use super::*;

fn fixtures_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/audio")
        .canonicalize()
        .expect("fixtures directory present")
}

fn read(fixture: &str) -> ParsedMetadata {
    read_from_file(&fixtures_dir().join(fixture), &InputLimits::defaults()).unwrap()
}

#[test]
fn tags_and_parameters_parse_from_fixtures() {
    // Fixture tags are generated by scripts/gen-fixtures.mjs (the FLAC
    // variant renames the tone: "Flac Tone").
    let mp3 = read("tone-short.mp3");
    assert_eq!(mp3.title.as_deref(), Some("Echo Tone"));
    assert_eq!(mp3.artist.as_deref(), Some("Echo Fixtures"));
    assert_eq!(mp3.album.as_deref(), Some("Fixture Album"));
    assert!(
        mp3.parameters.sample_rate_hz == Some(44_100),
        "stream parameters come from the container: {:?}",
        mp3.parameters
    );
    // Duration/format are probe-owned, never tag-owned.
    assert!(mp3.duration.is_none());
    assert!(mp3.warnings.is_empty());

    let flac = read("tone-short.flac");
    assert_eq!(flac.title.as_deref(), Some("Flac Tone"));
    assert!(
        flac.cover.is_some(),
        "the FLAC fixture embeds the generated cover"
    );

    // MP4/AAC tags parse through the same lofty path (the fixture carries
    // the standard title/artist/album generated by scripts/gen-fixtures.mjs).
    let m4a = read("tone-short.m4a");
    assert_eq!(m4a.title.as_deref(), Some("M4A Tone"));
    assert_eq!(m4a.artist.as_deref(), Some("Echo Fixtures"));
    assert_eq!(m4a.album.as_deref(), Some("Fixture Album"));
    assert!(
        m4a.parameters.sample_rate_hz == Some(44_100),
        "stream parameters come from the container: {:?}",
        m4a.parameters
    );
    // Duration/format are probe-owned, never tag-owned.
    assert!(m4a.duration.is_none());
    assert!(m4a.warnings.is_empty());
}

#[test]
fn ape_unknown_items_supply_cover_and_unsynced_lyrics() {
    use lofty::tag::{ItemValue, TagItem};

    let mut tag = Tag::new(TagType::Ape);
    tag.insert_unchecked(TagItem::new(
        ItemKey::Unknown("COVER ART (FRONT)".to_owned()),
        ItemValue::Binary(
            [
                b"Cover Art (Front).jpg\0".as_slice(),
                &[0xff, 0xd8, 0xff, 0xe0, 0, 0x10, b'J', b'F', b'I', b'F'],
            ]
            .concat(),
        ),
    ));
    tag.insert_unchecked(TagItem::new(
        ItemKey::Unknown("UNSYNCEDLYRICS".to_owned()),
        ItemValue::Text("[00:01.00]first line".to_owned()),
    ));

    assert_eq!(
        lyrics_from_tag(&tag),
        Some("[00:01.00]first line"),
        "common APE lyrics key is not in lofty's normalized map"
    );

    let mut parsed = ParsedMetadata::default();
    read_cover(&tag, InputLimits::defaults().cover, &mut parsed);
    let cover = parsed.cover.expect("APE binary picture becomes a cover");
    assert_eq!(cover.mime, "image/jpeg");
    assert_eq!(&cover.bytes[..4], &[0xff, 0xd8, 0xff, 0xe0]);
    assert!(parsed.warnings.is_empty());
}

fn quicktime_atom_bytes(atom_type: [u8; 4], payload: &[u8]) -> Vec<u8> {
    let size = u32::try_from(payload.len() + 8).unwrap();
    [size.to_be_bytes().as_slice(), &atom_type, payload].concat()
}

fn quicktime_text_payload(value: &str) -> Vec<u8> {
    let mut payload = Vec::with_capacity(value.len() + 4);
    payload.extend_from_slice(&u16::try_from(value.len()).unwrap().to_be_bytes());
    payload.extend_from_slice(&[0x55, 0xc4]);
    payload.extend_from_slice(value.as_bytes());
    payload
}

fn quicktime_text_payload_with_trailing_language(value: &str) -> Vec<u8> {
    let mut payload = Vec::with_capacity(value.len() + 4);
    payload.extend_from_slice(&u16::try_from(value.len()).unwrap().to_be_bytes());
    payload.extend_from_slice(value.as_bytes());
    payload.extend_from_slice(&[0, 0]);
    payload
}

#[test]
fn quicktime_legacy_udta_atoms_supply_text_tags() {
    let udta_payload = [
        quicktime_atom_bytes(*b"\xa9nam", &quicktime_text_payload("旧标题")),
        quicktime_atom_bytes(*b"\xa9ART", &quicktime_text_payload("旧歌手")),
        quicktime_atom_bytes(*b"\xa9alb", &quicktime_text_payload("旧专辑")),
    ]
    .concat();
    let content = quicktime_atom_bytes(*b"moov", &quicktime_atom_bytes(*b"udta", &udta_payload));
    let mut parsed = ParsedMetadata::default();

    read_quicktime_udta_tags(&content, &InputLimits::defaults(), &mut parsed);

    assert_eq!(parsed.title.as_deref(), Some("旧标题"));
    assert_eq!(parsed.artist.as_deref(), Some("旧歌手"));
    assert_eq!(parsed.album.as_deref(), Some("旧专辑"));
    assert!(parsed.warnings.is_empty());

    let trailing_language = quicktime_text_payload_with_trailing_language("兼容文本");
    assert_eq!(
        quicktime_text(&trailing_language, 0, trailing_language.len()),
        Some("兼容文本")
    );
}

#[test]
fn quicktime_subtitle_payload_is_decoded() {
    let text = "[00:01.00]歌词";
    let mut payload = Vec::with_capacity(text.len() + 2);
    payload.extend_from_slice(&u16::try_from(text.len()).unwrap().to_be_bytes());
    payload.extend_from_slice(text.as_bytes());

    assert_eq!(quicktime_subtitle_text(&payload), Some(text));
}

/// Task 5.2: import sources are named from their bytes, before anything
/// is written to the library — the reader must accept content directly
/// and agree with the file-based read.
#[test]
fn tags_parse_from_in_memory_import_source_bytes() {
    let bytes = std::fs::read(fixtures_dir().join("tone-short.flac")).unwrap();
    let reader = || LoftyMetadataReader::new(RootRegistry::new());
    let from_bytes = reader().read_bytes(&bytes).unwrap();
    assert_eq!(from_bytes.title.as_deref(), Some("Flac Tone"));
    assert_eq!(from_bytes.artist.as_deref(), Some("Echo Fixtures"));
    // The content-based read agrees with the path-based read of the same
    // audio (the import naming and the committed record must not drift).
    let from_file = read("tone-short.flac");
    assert_eq!(from_bytes.title, from_file.title);
    assert_eq!(from_bytes.artist, from_file.artist);
    // Garbage content fails instead of producing a guessable name.
    assert!(reader().read_bytes(b"definitely not audio").is_err());
}

/// The MP4/AAC fixture agrees between the content-based and path-based
/// reads, so an `.m4a` import source is named from its bytes exactly like
/// the committed record it will become.
#[test]
fn m4a_tags_parse_from_in_memory_import_source_bytes() {
    let bytes = std::fs::read(fixtures_dir().join("tone-short.m4a")).unwrap();
    let reader = || LoftyMetadataReader::new(RootRegistry::new());
    let from_bytes = reader().read_bytes(&bytes).unwrap();
    assert_eq!(from_bytes.title.as_deref(), Some("M4A Tone"));
    assert_eq!(from_bytes.artist.as_deref(), Some("Echo Fixtures"));
    // The content-based read agrees with the path-based read of the same
    // audio (the import naming and the committed record must not drift).
    let from_file = read("tone-short.m4a");
    assert_eq!(from_bytes.title, from_file.title);
    assert_eq!(from_bytes.artist, from_file.artist);
}

/// Task 12.7: hostile/malicious metadata must never panic, never leak an
/// unbounded resource, and must keep the audio record importable. Control
/// characters and NFKC junk in tags/lyrics are cleaned; oversized fields
/// are dropped with a diagnostic (the real boundaries are the 4 KiB tag /
/// 2 MiB lyrics / 20 MiB cover inputs, asserted separately in
/// `input_limits_skip_assets_but_keep_song_fields`).
#[test]
fn hostile_tags_with_controls_and_oversized_text_are_cleaned_or_diagnosed() {
    // Control characters in the display title.
    let cleaned_title = clean_display_text("晴\u{0}\u{7f}天\t夜里");
    assert_eq!(
        cleaned_title, "晴天 夜里",
        "null/DEL stripped from tags; tab collapses to a display space"
    );

    // Null bytes and DEL hidden in lyrics are stripped per line, and the
    // empty-line collapse keeps the structure.
    let cleaned_lyrics = clean_lyrics_text("第一行\u{0}\n\u{7f}\n第二行");
    assert_eq!(cleaned_lyrics, "第一行\n第二行");
    assert!(!cleaned_lyrics.contains('\u{0}'));

    // An over-limit field (simulated at the same boundary the reader uses)
    // is dropped with the lyrics warning, never returned partially.
    let mut parsed = ParsedMetadata::default();
    let big = "\u{8d85}\u{9650}".repeat(1_048_576 / 2); // ~2 MiB
    let result = limited_lyrics(Some(&big), 2 * 1024 * 1024, &mut parsed);
    assert!(
        result.is_none(),
        "a bytes-over-limit lyrics field is dropped, not returned"
    );
    assert!(
        parsed
            .warnings
            .iter()
            .any(|w| w.kind == ParseWarningKind::LyricsLimit),
        "the over-limit lyrics field records a lyrics_limit diagnostic"
    );
}

/// Copy a fixture into a temp dir and write over-limit fields with lofty
/// (the only way to build a genuinely over-limit tag without shipping a
/// giant fixture). The temp dir is intentionally kept alive for the test.
fn write_oversized_fixture(fixture: &str) -> std::path::PathBuf {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join(fixture);
    std::fs::copy(fixtures_dir().join(fixture), &path).unwrap();
    let mut tagged = lofty::read_from_path(&path).unwrap();
    let has_primary = tagged.primary_tag().is_some();
    let tag = if has_primary {
        tagged.primary_tag_mut().expect("checked above")
    } else {
        tagged.first_tag_mut().expect("fixture carries a tag")
    };
    tag.set_title("\u{957f}".repeat(64)); // 192 bytes > the 32-byte limit
    tag.insert_text(
        ItemKey::Lyrics,
        "\u{8d85}\u{9650}\u{6b4c}\u{8bcd}".repeat(64), // 256 bytes > the 64-byte limit
    );
    tagged
        .save_to_path(&path, lofty::config::WriteOptions::default())
        .unwrap();
    std::mem::forget(dir);
    path
}

#[test]
fn input_limits_skip_assets_but_keep_song_fields() {
    let oversized = write_oversized_fixture("tone-short.flac");
    let limits = InputLimits {
        tag_field: 32,
        lyrics: 64,
        cover: 128,
    };
    let meta = read_from_file(&oversized, &limits).unwrap();
    assert!(
        meta.title.is_none(),
        "over-limit tag fields are dropped: {meta:?}"
    );
    assert!(
        meta.embedded_lyrics.is_none(),
        "over-limit lyrics are dropped: {meta:?}"
    );
    assert!(
        meta.cover.is_none(),
        "over-limit covers are skipped: {meta:?}"
    );
    let kinds: Vec<_> = meta.warnings.iter().map(|w| w.kind).collect();
    assert!(kinds.contains(&ParseWarningKind::TagLimit), "{kinds:?}");
    assert!(kinds.contains(&ParseWarningKind::LyricsLimit), "{kinds:?}");
    assert!(kinds.contains(&ParseWarningKind::CoverLimit), "{kinds:?}");
    // The audio record is still importable: stream parameters survive.
    assert_eq!(meta.parameters.sample_rate_hz, Some(44_100));
}

#[test]
fn clean_display_text_strips_controls_and_normalizes() {
    assert_eq!(clean_display_text("晴\u{0}天"), "晴天");
    assert_eq!(clean_display_text("  A\u{7f}B  "), "AB");
    assert_eq!(clean_display_text("ＡＢ"), "AB", "NFKC compatibility fold");
    assert_eq!(clean_display_text("line1\nline2"), "line1 line2");
}

#[test]
fn clean_lyrics_text_keeps_line_structure() {
    assert_eq!(clean_lyrics_text("第一行\n\n第二行\u{0}"), "第一行\n第二行");
    assert_eq!(clean_lyrics_text("ＡＢ\nＣＤ"), "AB\nCD");
    assert_eq!(clean_lyrics_text("\n\n"), "");
}

#[test]
fn mime_of_maps_every_variant_with_a_default_fallback() {
    use lofty::picture::MimeType;
    assert_eq!(mime_of(Some(&MimeType::Png)), "image/png");
    assert_eq!(mime_of(Some(&MimeType::Jpeg)), "image/jpeg");
    assert_eq!(mime_of(Some(&MimeType::Tiff)), "image/tiff");
    assert_eq!(mime_of(Some(&MimeType::Bmp)), "image/bmp");
    assert_eq!(mime_of(Some(&MimeType::Gif)), "image/gif");
    assert_eq!(
        mime_of(Some(&MimeType::Unknown("image/webp".to_owned()))),
        "image/webp"
    );
    assert_eq!(mime_of(None), "application/octet-stream");
}

/// The reader resolves the path through the root registry and maps a
/// missing file to an io error — the branch the adapter surfaces to the
/// scan pipeline before the layout probe.
#[test]
fn read_of_an_unregistered_root_or_missing_file_is_an_error() {
    let reader = LoftyMetadataReader::new(RootRegistry::new());
    let ghost = LibraryRootId::new();
    let path = RelativeMediaPath::new("missing.flac").unwrap();
    assert!(reader.read(ghost, &path).is_err());

    let dir = tempfile::tempdir().unwrap();
    let registry = RootRegistry::new();
    let root = LibraryRootId::new();
    registry.register(root, dir.path());
    let reader = LoftyMetadataReader::new(registry);
    assert!(reader.read(root, &path).is_err());
    // The in-memory reader rejects garbage content and returns a
    // corrupt-media classification, not a panic.
    let error = reader.read_bytes(b"definitely not audio").unwrap_err();
    assert_eq!(error.code(), "corrupt_media");
}

/// Tag values that collapse to empty after cleanup (`None`), and
/// over-limit values dropped with the right warning kind, stay consistent
/// between the field and lyrics variants.
#[test]
fn limited_field_and_lyrics_clean_to_empty_or_warn() {
    let mut parsed = ParsedMetadata::default();
    // Whitespace-only and control-only values collapse to None.
    assert_eq!(
        limited_field(Some("   "), "tag:title", 1024, &mut parsed),
        None
    );
    assert_eq!(
        limited_field(Some(""), "tag:title", 1024, &mut parsed),
        None
    );
    assert_eq!(limited_lyrics(Some("\u{0}\n\n"), 1024, &mut parsed), None);
    assert_eq!(limited_lyrics(Some(""), 1024, &mut parsed), None);
    assert!(parsed.warnings.is_empty(), "empty values never warn");

    // An over-limit field records exactly the TagLimit warning.
    let mut over = ParsedMetadata::default();
    let long = "长".repeat(200);
    let value = limited_field(Some(&long), "tag:genre", 32, &mut over);
    assert!(value.is_none());
    assert_eq!(over.warnings.len(), 1);
    assert_eq!(over.warnings[0].kind, ParseWarningKind::TagLimit);
    assert_eq!(over.warnings[0].field, "tag:genre");
}

/// The fixture carry no album-artist or track-number; the untouched tag
/// fields stay `None` rather than producing junk values.
#[test]
fn absent_tags_stay_none_on_real_fixtures() {
    let mp3 = read("tone-short.mp3");
    assert_eq!(mp3.album_artist, None);
    assert_eq!(mp3.track, None);
    // The fixture embeds no cover; the parameters still come from the
    // container (probe-owned duration stays unset).
    assert!(mp3.cover.is_none());
    assert!(mp3.duration.is_none());
    assert!(
        mp3.parameters.sample_rate_hz == Some(44_100),
        "stream parameters parsed without a tag-aware branch"
    );
}

/// A real tag-less WAV must read as `Ok` with empty fields, never fail
/// the pipeline: the missing-tag fallback only works when a no-tag file is
/// a successful empty parse, not an error.
#[test]
fn tagless_wav_reads_as_ok_with_empty_fields() {
    let wav = read("tone-short.wav");
    assert_eq!(wav.title, None, "a real wav has no readable tags");
    assert_eq!(wav.artist, None);
    assert_eq!(wav.album, None);
    assert!(wav.duration.is_none(), "duration is probe-owned");
    assert!(wav.warnings.is_empty());
    assert_eq!(
        wav.parameters.sample_rate_hz,
        Some(44_100),
        "container stream parameters still parse: {:?}",
        wav.parameters
    );
}

fn riff_info_wav() -> Vec<u8> {
    fn chunk(kind: [u8; 4], value: &[u8]) -> Vec<u8> {
        let mut bytes = [
            kind.as_slice(),
            &u32::try_from(value.len() + 1).unwrap().to_le_bytes(),
            value,
            &[0],
        ]
        .concat();
        if value.len() % 2 == 0 {
            bytes.push(0);
        }
        bytes
    }

    let mut list_payload = b"INFO".to_vec();
    list_payload.extend(chunk(*b"INAM", "WAV 标题".as_bytes()));
    list_payload.extend(chunk(*b"IART", "WAV 歌手".as_bytes()));
    list_payload.extend(chunk(*b"IPRD", "WAV 专辑".as_bytes()));
    let list = [
        b"LIST".as_slice(),
        &u32::try_from(list_payload.len()).unwrap().to_le_bytes(),
        &list_payload,
    ]
    .concat();

    let fmt = [
        b"fmt ".as_slice(),
        &16u32.to_le_bytes(),
        &1u16.to_le_bytes(),
        &1u16.to_le_bytes(),
        &8_000u32.to_le_bytes(),
        &16_000u32.to_le_bytes(),
        &2u16.to_le_bytes(),
        &16u16.to_le_bytes(),
    ]
    .concat();
    let data = [b"data".as_slice(), &2u32.to_le_bytes(), &[0, 0]].concat();
    let body = [b"WAVE".as_slice(), &fmt, &list, &data].concat();
    [
        b"RIFF".as_slice(),
        &u32::try_from(body.len()).unwrap().to_le_bytes(),
        &body,
    ]
    .concat()
}

#[test]
fn riff_info_wav_tags_are_read() {
    let parsed = read_from_reader(Cursor::new(riff_info_wav()), &InputLimits::defaults()).unwrap();

    assert_eq!(parsed.title.as_deref(), Some("WAV 标题"));
    assert_eq!(parsed.artist.as_deref(), Some("WAV 歌手"));
    assert_eq!(parsed.album.as_deref(), Some("WAV 专辑"));
    assert_eq!(parsed.parameters.sample_rate_hz, Some(8_000));
    assert!(parsed.warnings.is_empty());
}
