// Auto-generated by echo-desktop ipc::generate — do not edit.
// Run `pnpm generate:ipc` (or cargo test) and commit the result.
// The generator mirrors the serde DTOs: camelCase, readonly, no absolute paths.

export interface IpcErrorDto {
  readonly code: string;
  readonly messageKey: string;
  readonly retryable: boolean;
  readonly operationId?: string;
  readonly field?: string;
}

export type IpcResult<T> = T | IpcErrorDto;

export interface UiQueueEntry {
  readonly entryId: string;
  readonly songId: string | null;
  readonly title: string | null;
  readonly isCurrent: boolean;
  readonly failed: boolean;
  readonly blocked: boolean;
  readonly canImport: boolean;
  readonly artist: string | null;
  readonly durationS: number | null;
  readonly coverKey: string | null;
}

export interface UiPlayerSnapshot {
  readonly state: 'stopped' | 'loading' | 'playing' | 'paused' | 'ended' | 'failed';
  readonly position: number | null;
  readonly duration: number | null;
  readonly volume: number;
  readonly muted: boolean;
  readonly currentQueueEntryId: string | null;
  readonly currentSongId: string | null;
  readonly queueLen: number;
  readonly mode: 'sequential' | 'shuffle' | 'repeatOne';
  readonly currentTitle: string | null;
  readonly currentArtist?: string | null;
  readonly currentAlbum?: string | null;
  readonly currentCoverKey?: string | null;
  readonly currentLyrics?: SongLyricsDto | null;
  readonly currentCanImport: boolean;
  readonly queue: readonly UiQueueEntry[];
}

export interface BootstrapSnapshot {
  readonly ready: boolean;
  readonly writesAllowed: boolean;
  readonly activeRoot?: string;
  readonly recoveredOperations: number;
}

export type SongAvailability = 'available' | 'missing' | 'pending-delete';

export interface SongView {
  readonly id: string;
  readonly title?: string;
  readonly artist?: string;
  readonly album?: string;
  readonly durationS?: number;
  readonly favorite: boolean;
  readonly playCount: number;
  readonly availability: SongAvailability;
  readonly relativePath: string;
}

export interface PagedSongs {
  readonly items: readonly SongView[];
  readonly nextCursor?: string;
  readonly isLast: boolean;
}

export interface LibraryCountsDto {
  readonly all: number;
  readonly favorites: number;
  readonly recent: number;
}

export interface PlaylistView {
  readonly id: string;
  readonly name: string;
  readonly memberCount: number;
  readonly coverKey?: string;
  readonly automaticCoverKey?: string;
  readonly hasCustomCover: boolean;
}

export interface LibraryRootStatusDto {
  readonly configured: boolean;
  readonly readOnly: boolean;
  readonly activeRoot: string;
  readonly manifestHealed: boolean;
  readonly controlPlaneReadOnly: boolean;
  readonly continuedSongs: number;
  readonly continuedFavorites: number;
  readonly continuedPlaylists: number;
  readonly continuedMembers: number;
  readonly continuedPlayStats: number;
  readonly unusableRecords: number;
}

export interface LibraryStatus {
  readonly configured: boolean;
  readonly readOnly: boolean;
  readonly unavailable: boolean;
  readonly scanning: boolean;
  readonly activeRoot?: string;
}

export interface ScanSnapshot {
  readonly generation: number;
  readonly cancelled: boolean;
  readonly state: string;
  readonly discovered: number;
  readonly processed: number;
  readonly created: number;
  readonly updated: number;
  readonly missing: number;
  readonly skipped: number;
  readonly failed: number;
}

export interface SongDetailView {
  readonly songId: string;
  readonly relativePath: string;
  readonly title?: string;
  readonly artist?: string;
  readonly album?: string;
  readonly durationS?: number;
  readonly format?: string;
  readonly playCount: number;
  readonly favorite: boolean;
  readonly hasCover: boolean;
  readonly lyrics: string;
  readonly availability: SongAvailability;
}

export type ImportResultDto =
  | { readonly kind: 'imported'; readonly operationId: string; readonly songId: string; readonly relativePath: string; readonly renamed: boolean }
  | { readonly kind: 'duplicate'; readonly existingSongId: string }
  | { readonly kind: 'skipped' }
  | { readonly kind: 'libraryUnavailable' }
  | { readonly kind: 'failed'; readonly code: string; readonly message: string };

export interface ImportBatchDto {
  readonly results: readonly ImportResultDto[];
}

export interface RevealResultDto {
  readonly songId: string;
  readonly relativePath: string;
  readonly revealed: boolean;
}

export interface LyricsLineView {
  readonly seconds: number;
  readonly text: string;
}

export interface SongLyricsDto {
  readonly source: 'override' | 'embedded' | 'sidecar' | null;
  readonly timed: boolean;
  readonly lines: readonly LyricsLineView[];
  readonly plainText: string;
  readonly parseError?: string | null;
}

export type Theme = 'coral' | 'cobalt' | 'turquoise';
export type CloseBehavior = 'exit' | 'background';

/** Generated command name → successful return DTO contract. */
export interface IpcCommandResultMap {
  readonly get_bootstrap_state: BootstrapSnapshot;
  readonly library_status: LibraryStatus;
  readonly all_songs: PagedSongs;
  readonly search: PagedSongs;
  readonly favorites: PagedSongs;
  readonly recent: readonly SongView[];
  readonly library_counts: LibraryCountsDto;
  readonly playlists: readonly PlaylistView[];
  readonly playlist_members: readonly SongView[];
  readonly song_detail: SongDetailView;
  readonly song_cover_keys: Readonly<Record<string, string>>;
  readonly set_favorite: SongView;
  readonly create_playlist: string;
  readonly rename_playlist: void;
  readonly set_playlist_cover: void;
  readonly delete_playlist: void;
  readonly add_to_playlists: void;
  readonly remove_playlist_song: void;
  readonly delete_song: string;
  readonly undo_delete: string;
  readonly choose_library_root: LibraryRootStatusDto | null;
  readonly choose_and_import_files: ImportBatchDto | null;
  readonly reveal_song: RevealResultDto;
  readonly start_scan: ScanSnapshot;
  readonly cancel_scan: boolean;
  readonly set_theme: void;
  readonly set_close_behavior: void;
  readonly get_close_behavior: CloseBehavior;
  readonly play_playlist_context: void;
  readonly play_library_context: void;
  readonly restore_playback_session: string;
  readonly play_temporary_file: void;
  readonly import_current_temporary_file: ImportResultDto;
  readonly player_control: void;
  readonly queue_command: void;
  readonly set_volume: void;
  readonly toggle_mute: void;
  readonly seek: void;
  readonly get_lyrics: SongLyricsDto;
}
