// Auto-generated by echo-desktop ipc::generate — do not edit.
// Run `pnpm generate:ipc` (or cargo test) and commit the result.
// The generator mirrors the serde DTOs: camelCase, readonly, no absolute paths.

export interface IpcErrorDto {
  readonly code: string;
  readonly messageKey: string;
  readonly retryable: boolean;
  readonly operationId?: string;
  readonly field?: string;
}

export type IpcResult<T> = T | IpcErrorDto;

export interface UiQueueEntry {
  readonly entryId: string;
  readonly songId: string | null;
  readonly title: string | null;
  readonly isCurrent: boolean;
  readonly failed: boolean;
  readonly blocked: boolean;
  readonly canImport: boolean;
  readonly artist: string | null;
  readonly durationS: number | null;
  readonly coverKey: string | null;
}

export interface UiPlayerSnapshot {
  readonly state: 'stopped' | 'loading' | 'playing' | 'paused' | 'ended' | 'failed';
  readonly position: number | null;
  readonly duration: number | null;
  readonly volume: number;
  readonly muted: boolean;
  readonly currentQueueEntryId: string | null;
  readonly currentSongId: string | null;
  readonly queueLen: number;
  readonly mode: 'sequential' | 'shuffle' | 'repeatOne';
  readonly currentTitle: string | null;
  readonly currentCanImport: boolean;
  readonly queue: readonly UiQueueEntry[];
}

export interface BootstrapSnapshot {
  readonly ready: boolean;
  readonly writesAllowed: boolean;
  readonly activeRoot?: string;
  readonly recoveredOperations: number;
}

export type SongAvailability = 'available' | 'missing' | 'pending-delete';

export interface SongView {
  readonly id: string;
  readonly title?: string;
  readonly artist?: string;
  readonly album?: string;
  readonly durationS?: number;
  readonly favorite: boolean;
  readonly playCount: number;
  readonly availability: SongAvailability;
  readonly relativePath: string;
}

export interface PagedSongs {
  readonly items: readonly SongView[];
  readonly nextCursor?: string;
  readonly isLast: boolean;
}

export interface LibraryCountsDto {
  readonly all: number;
  readonly favorites: number;
  readonly recent: number;
}

export interface PlaylistView {
  readonly id: string;
  readonly name: string;
  readonly memberCount: number;
  readonly coverKey?: string;
  readonly automaticCoverKey?: string;
  readonly hasCustomCover: boolean;
}

export interface LibraryRootStatusDto {
  readonly configured: boolean;
  readonly readOnly: boolean;
  readonly activeRoot: string;
}

export type ImportResultDto =
  | { readonly kind: 'imported'; readonly operationId: string; readonly songId: string; readonly relativePath: string }
  | { readonly kind: 'duplicate'; readonly existingSongId: string }
  | { readonly kind: 'unsupported' }
  | { readonly kind: 'libraryUnavailable' }
  | { readonly kind: 'failed'; readonly code: string; readonly message: string };

export interface ImportBatchDto {
  readonly results: readonly ImportResultDto[];
}

export interface RevealResultDto {
  readonly songId: string;
  readonly relativePath: string;
  readonly revealed: boolean;
}

export interface LyricsLineView {
  readonly seconds: number;
  readonly text: string;
}

export interface SongLyricsDto {
  readonly source: 'override' | 'embedded' | 'sidecar' | null;
  readonly timed: boolean;
  readonly lines: readonly LyricsLineView[];
  readonly plainText: string;
  readonly parseError?: string | null;
}

export type Theme = 'coral' | 'cobalt' | 'turquoise';
export type CloseBehavior = 'exit' | 'background';
