// Auto-generated by echo-desktop ipc::generate — do not edit.
// Run `pnpm generate:ipc` (or cargo test) and commit the result.
// The generator mirrors the serde DTOs: camelCase, readonly, no absolute paths.

export interface IpcErrorDto {
  readonly code: string;
  readonly messageKey: string;
  readonly retryable: boolean;
  readonly operationId?: string;
  readonly field?: string;
}

export type IpcResult<T> = T | IpcErrorDto;

export interface BootstrapSnapshot {
  readonly ready: boolean;
  readonly writesAllowed: boolean;
  readonly activeRoot?: string;
  readonly recoveredOperations: number;
}

export type SongAvailability = 'available' | 'missing' | 'pending-delete';

export interface SongView {
  readonly id: string;
  readonly title?: string;
  readonly artist?: string;
  readonly album?: string;
  readonly durationS?: number;
  readonly favorite: boolean;
  readonly playCount: number;
  readonly availability: SongAvailability;
  readonly relativePath: string;
}

export interface PagedSongs {
  readonly items: readonly SongView[];
  readonly nextCursor?: string;
  readonly isLast: boolean;
}

export interface PlaylistView {
  readonly id: string;
  readonly name: string;
  readonly memberCount: number;
}

export type Theme = 'coral' | 'light' | 'dark';
export type CloseBehavior = 'exit' | 'background';
