//! Read-only TypeScript type generation (task 7.2, design §10).
//!
//! A deterministic, curated generator that emits a `.d.ts` from the IPC DTOs.
//! The output is checked into the repo; CI runs the generator and fails on any
//! uncommitted diff (`git diff --exit-code`), so Rust/TS contract drift is
//! detected at build time. Output uses `readonly` throughout and camelCase
//! field names to match the serde DTOs.

/// The complete, deterministic TypeScript module for the IPC contract.
#[must_use]
pub fn generated_typescript() -> String {
    let mut out = String::with_capacity(8 * 1024);
    out.push_str("// Auto-generated by echo-desktop ipc::generate — do not edit.\n");
    out.push_str("// Run `pnpm generate:ipc` (or cargo test) and commit the result.\n");
    out.push_str(
        "// The generator mirrors the serde DTOs: camelCase, readonly, no absolute paths.\n\n",
    );
    out.push_str("export interface IpcErrorDto {\n");
    out.push_str("  readonly code: string;\n");
    out.push_str("  readonly messageKey: string;\n");
    out.push_str("  readonly retryable: boolean;\n");
    out.push_str("  readonly operationId?: string;\n");
    out.push_str("  readonly field?: string;\n");
    out.push_str("}\n\n");
    out.push_str("export type IpcResult<T> = T | IpcErrorDto;\n\n");

    out.push_str("export interface BootstrapSnapshot {\n");
    out.push_str("  readonly ready: boolean;\n");
    out.push_str("  readonly writesAllowed: boolean;\n");
    out.push_str("  readonly activeRoot?: string;\n");
    out.push_str("  readonly recoveredOperations: number;\n");
    out.push_str("}\n\n");

    out.push_str("export type SongAvailability = 'available' | 'missing' | 'pending-delete';\n\n");
    out.push_str("export interface SongView {\n");
    out.push_str("  readonly id: string;\n");
    out.push_str("  readonly title?: string;\n");
    out.push_str("  readonly artist?: string;\n");
    out.push_str("  readonly album?: string;\n");
    out.push_str("  readonly durationS?: number;\n");
    out.push_str("  readonly favorite: boolean;\n");
    out.push_str("  readonly playCount: number;\n");
    out.push_str("  readonly availability: SongAvailability;\n");
    out.push_str("  readonly relativePath: string;\n");
    out.push_str("}\n\n");

    out.push_str("export interface PagedSongs {\n");
    out.push_str("  readonly items: readonly SongView[];\n");
    out.push_str("  readonly nextCursor?: string;\n");
    out.push_str("  readonly isLast: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LibraryCountsDto {\n");
    out.push_str("  readonly all: number;\n");
    out.push_str("  readonly favorites: number;\n");
    out.push_str("  readonly recent: number;\n");
    out.push_str("}\n\n");

    out.push_str("export interface PlaylistView {\n");
    out.push_str("  readonly id: string;\n");
    out.push_str("  readonly name: string;\n");
    out.push_str("  readonly memberCount: number;\n");
    out.push_str("  readonly coverKey?: string;\n");
    out.push_str("  readonly automaticCoverKey?: string;\n");
    out.push_str("  readonly hasCustomCover: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LibraryRootStatusDto {\n");
    out.push_str("  readonly configured: boolean;\n");
    out.push_str("  readonly readOnly: boolean;\n");
    out.push_str("  readonly activeRoot: string;\n");
    out.push_str("}\n\n");

    out.push_str("export type ImportResultDto =\n");
    out.push_str("  | { readonly kind: 'imported'; readonly operationId: string; readonly songId: string; readonly relativePath: string }\n");
    out.push_str("  | { readonly kind: 'duplicate'; readonly existingSongId: string }\n");
    out.push_str("  | { readonly kind: 'unsupported' }\n");
    out.push_str("  | { readonly kind: 'libraryUnavailable' }\n");
    out.push_str(
        "  | { readonly kind: 'failed'; readonly code: string; readonly message: string };\n\n",
    );

    out.push_str("export interface ImportBatchDto {\n");
    out.push_str("  readonly results: readonly ImportResultDto[];\n");
    out.push_str("}\n\n");

    out.push_str("export interface RevealResultDto {\n");
    out.push_str("  readonly songId: string;\n");
    out.push_str("  readonly relativePath: string;\n");
    out.push_str("  readonly revealed: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LyricsLineView {\n");
    out.push_str("  readonly seconds: number;\n");
    out.push_str("  readonly text: string;\n");
    out.push_str("}\n\n");

    out.push_str("export interface SongLyricsDto {\n");
    out.push_str("  readonly source: 'override' | 'embedded' | 'sidecar' | null;\n");
    out.push_str("  readonly timed: boolean;\n");
    out.push_str("  readonly lines: readonly LyricsLineView[];\n");
    out.push_str("  readonly plainText: string;\n");
    out.push_str("  readonly parseError?: string | null;\n");
    out.push_str("}\n\n");

    out.push_str("export type Theme = 'coral' | 'cobalt' | 'turquoise';\n");
    out.push_str("export type CloseBehavior = 'exit' | 'background';\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Drift detection: the committed generated file must equal the current
    /// generator output. CI additionally runs `git diff --exit-code`, but this
    /// test makes `cargo test -p echo-desktop` catch the same divergence.
    #[test]
    fn committed_generated_file_is_in_sync_with_the_generator() {
        let committed = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .expect("crate dir")
                .parent()
                .expect("workspace")
                .join("apps/desktop/src/ipc/ipc-types.generated.ts"),
        )
        .expect("generated file committed");
        assert_eq!(
            committed,
            generated_typescript(),
            "IPC types drifted; run `cargo run -p echo-desktop --bin echo-generate-ipc` and commit"
        );
    }

    #[test]
    fn generated_types_are_readonly_and_camel_case() {
        let ts = generated_typescript();
        assert!(ts.contains("readonly "), "all fields readonly");
        assert!(ts.contains("relativePath"), "camelCase field");
        assert!(ts.contains("nextCursor"), "camelCase field");
        assert!(!ts.contains("relative_path"), "no snake_case leaks");
        assert!(!ts.contains("absolutePath"), "no absolute path type");
        assert!(ts.contains("IpcErrorDto"), "error DTO present");
        // Determinism: run twice -> identical.
        assert_eq!(ts, generated_typescript());
    }

    #[test]
    fn generated_types_dont_materialize_private_impl_details() {
        let ts = generated_typescript();
        let forbidden = ["Mutex", "ScanDeps", "PathBuf", "core::", "echo_core"];
        for token in forbidden {
            assert!(!ts.contains(token), "ICD leaks {token}");
        }
    }
}
