//! Read-only TypeScript type generation (task 7.2, design §10).
//!
//! A deterministic, curated generator that emits a `.d.ts` from the IPC DTOs.
//! The output is checked into the repo; CI runs the generator and fails on any
//! uncommitted diff (`git diff --exit-code`), so Rust/TS contract drift is
//! detected at build time. Output uses `readonly` throughout and camelCase
//! field names to match the serde DTOs.

/// The complete, deterministic TypeScript module for the IPC contract.
#[must_use]
#[allow(clippy::too_many_lines)] // Keeps the generated contract together; task 4 splits its helpers with the generator work.
pub fn generated_typescript() -> String {
    let mut out = String::with_capacity(8 * 1024);
    out.push_str("// Auto-generated by echo-desktop ipc::generate — do not edit.\n");
    out.push_str("// Run `pnpm generate:ipc` (or cargo test) and commit the result.\n");
    out.push_str(
        "// The generator mirrors the serde DTOs: camelCase, readonly, no absolute paths.\n\n",
    );
    out.push_str("export interface IpcErrorDto {\n");
    out.push_str("  readonly code: string;\n");
    out.push_str("  readonly messageKey: string;\n");
    out.push_str("  readonly retryable: boolean;\n");
    out.push_str("  readonly operationId?: string;\n");
    out.push_str("  readonly field?: string;\n");
    out.push_str("}\n\n");
    out.push_str("export type IpcResult<T> = T | IpcErrorDto;\n\n");

    // Player snapshots travel on the typed `player://snapshot` event rather
    // than a command response, but they are still a cross-process IPC DTO.
    // Keep this canonical definition generated alongside command DTOs so UI
    // consumers cannot drift from the Rust serde contract.
    out.push_str("export interface UiQueueEntry {\n");
    out.push_str("  readonly entryId: string;\n");
    out.push_str("  readonly songId: string | null;\n");
    out.push_str("  readonly title: string | null;\n");
    out.push_str("  readonly isCurrent: boolean;\n");
    out.push_str("  readonly failed: boolean;\n");
    out.push_str("  readonly blocked: boolean;\n");
    out.push_str("  readonly canImport: boolean;\n");
    out.push_str("  readonly artist: string | null;\n");
    out.push_str("  readonly durationS: number | null;\n");
    out.push_str("  readonly coverKey: string | null;\n");
    out.push_str("}\n\n");
    out.push_str("export interface UiPlayerSnapshot {\n");
    out.push_str(
        "  readonly state: 'stopped' | 'loading' | 'playing' | 'paused' | 'ended' | 'failed';\n",
    );
    out.push_str("  readonly position: number | null;\n");
    out.push_str("  readonly duration: number | null;\n");
    out.push_str("  readonly volume: number;\n");
    out.push_str("  readonly muted: boolean;\n");
    out.push_str("  readonly currentQueueEntryId: string | null;\n");
    out.push_str("  readonly currentSongId: string | null;\n");
    out.push_str("  readonly queueLen: number;\n");
    out.push_str("  readonly mode: 'sequential' | 'shuffle' | 'repeatOne';\n");
    out.push_str("  readonly currentTitle: string | null;\n");
    out.push_str("  readonly currentArtist?: string | null;\n");
    out.push_str("  readonly currentAlbum?: string | null;\n");
    out.push_str("  readonly currentCoverKey?: string | null;\n");
    out.push_str("  readonly currentLyrics?: SongLyricsDto | null;\n");
    out.push_str("  readonly currentCanImport: boolean;\n");
    out.push_str("  readonly queue: readonly UiQueueEntry[];\n");
    out.push_str("}\n\n");

    out.push_str("export interface BootstrapSnapshot {\n");
    out.push_str("  readonly ready: boolean;\n");
    out.push_str("  readonly writesAllowed: boolean;\n");
    out.push_str("  readonly activeRoot?: string;\n");
    out.push_str("  readonly recoveredOperations: number;\n");
    out.push_str("}\n\n");

    out.push_str("export type SongAvailability = 'available' | 'missing' | 'pending-delete';\n\n");
    out.push_str("export type SongQuality = 'sq' | 'hq';\n\n");
    out.push_str("export interface SongView {\n");
    out.push_str("  readonly id: string;\n");
    out.push_str("  readonly title?: string;\n");
    out.push_str("  readonly artist?: string;\n");
    out.push_str("  readonly album?: string;\n");
    out.push_str("  readonly durationS?: number;\n");
    out.push_str("  readonly favorite: boolean;\n");
    out.push_str("  readonly playCount: number;\n");
    out.push_str("  readonly availability: SongAvailability;\n");
    out.push_str("  readonly relativePath: string;\n");
    out.push_str("  readonly quality?: SongQuality;\n");
    out.push_str("}\n\n");

    out.push_str("export interface PagedSongs {\n");
    out.push_str("  readonly items: readonly SongView[];\n");
    out.push_str("  readonly totalCount: number;\n");
    out.push_str("  readonly nextCursor?: string;\n");
    out.push_str("  readonly isLast: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface CatalogCollectionView {\n");
    out.push_str("  readonly kind: 'artist' | 'album';\n");
    out.push_str("  readonly artistKey: string;\n");
    out.push_str("  readonly albumKey?: string;\n");
    out.push_str("  readonly artist: string;\n");
    out.push_str("  readonly name: string;\n");
    out.push_str("  readonly songCount: number;\n");
    out.push_str("  readonly coverKey?: string;\n");
    out.push_str("  readonly hasCustomCover: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LibraryCountsDto {\n");
    out.push_str("  readonly all: number;\n");
    out.push_str("  readonly favorites: number;\n");
    out.push_str("  readonly recent: number;\n");
    out.push_str("  readonly artists: number;\n");
    out.push_str("  readonly albums: number;\n");
    out.push_str("}\n\n");

    out.push_str("export interface PlaylistView {\n");
    out.push_str("  readonly id: string;\n");
    out.push_str("  readonly name: string;\n");
    out.push_str("  readonly memberCount: number;\n");
    out.push_str("  readonly coverKey?: string;\n");
    out.push_str("  readonly automaticCoverKey?: string;\n");
    out.push_str("  readonly hasCustomCover: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LibraryRootStatusDto {\n");
    out.push_str("  readonly configured: boolean;\n");
    out.push_str("  readonly readOnly: boolean;\n");
    out.push_str("  readonly activeRoot: string;\n");
    out.push_str("  readonly manifestHealed: boolean;\n");
    out.push_str("  readonly controlPlaneReadOnly: boolean;\n");
    out.push_str("  readonly continuedSongs: number;\n");
    out.push_str("  readonly continuedFavorites: number;\n");
    out.push_str("  readonly continuedPlaylists: number;\n");
    out.push_str("  readonly continuedMembers: number;\n");
    out.push_str("  readonly continuedPlayStats: number;\n");
    out.push_str("  readonly unusableRecords: number;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LibraryStatus {\n");
    out.push_str("  readonly configured: boolean;\n");
    out.push_str("  readonly readOnly: boolean;\n");
    out.push_str("  readonly unavailable: boolean;\n");
    out.push_str("  readonly scanning: boolean;\n");
    out.push_str("  readonly activeRoot?: string;\n");
    out.push_str("}\n\n");

    out.push_str("export interface ScanSnapshot {\n");
    out.push_str("  readonly generation: number;\n");
    out.push_str("  readonly cancelled: boolean;\n");
    out.push_str("  readonly state: string;\n");
    out.push_str("  readonly discovered: number;\n");
    out.push_str("  readonly processed: number;\n");
    out.push_str("  readonly created: number;\n");
    out.push_str("  readonly updated: number;\n");
    out.push_str("  readonly missing: number;\n");
    out.push_str("  readonly skipped: number;\n");
    out.push_str("  readonly failed: number;\n");
    out.push_str("}\n\n");

    out.push_str("export interface SongDetailView {\n");
    out.push_str("  readonly songId: string;\n");
    out.push_str("  readonly relativePath: string;\n");
    out.push_str("  readonly title?: string;\n");
    out.push_str("  readonly artist?: string;\n");
    out.push_str("  readonly album?: string;\n");
    out.push_str("  readonly durationS?: number;\n");
    out.push_str("  readonly format?: string;\n");
    out.push_str("  readonly playCount: number;\n");
    out.push_str("  readonly favorite: boolean;\n");
    out.push_str("  readonly hasCover: boolean;\n");
    out.push_str("  readonly lyrics: string;\n");
    out.push_str("  readonly availability: SongAvailability;\n");
    out.push_str("}\n\n");

    out.push_str("export type ImportResultDto =\n");
    out.push_str("  | { readonly kind: 'imported'; readonly operationId: string; readonly songId: string; readonly relativePath: string; readonly renamed: boolean }\n");
    out.push_str("  | { readonly kind: 'duplicate'; readonly existingSongId: string }\n");
    out.push_str("  | { readonly kind: 'skipped' }\n");
    out.push_str("  | { readonly kind: 'libraryUnavailable' }\n");
    out.push_str(
        "  | { readonly kind: 'failed'; readonly code: string; readonly message: string };\n\n",
    );

    out.push_str("export interface ImportBatchDto {\n");
    out.push_str("  readonly results: readonly ImportResultDto[];\n");
    out.push_str("}\n\n");

    out.push_str("export interface RevealResultDto {\n");
    out.push_str("  readonly songId: string;\n");
    out.push_str("  readonly relativePath: string;\n");
    out.push_str("  readonly revealed: boolean;\n");
    out.push_str("}\n\n");

    out.push_str("export interface LyricsLineView {\n");
    out.push_str("  readonly seconds: number;\n");
    out.push_str("  readonly text: string;\n");
    out.push_str("}\n\n");

    out.push_str("export interface SongLyricsDto {\n");
    out.push_str("  readonly source: 'override' | 'embedded' | 'sidecar' | null;\n");
    out.push_str("  readonly timed: boolean;\n");
    out.push_str("  readonly lines: readonly LyricsLineView[];\n");
    out.push_str("  readonly plainText: string;\n");
    out.push_str("  readonly parseError?: string | null;\n");
    out.push_str("}\n\n");

    out.push_str("export type Theme = 'coral' | 'cobalt' | 'turquoise';\n");
    out.push_str("export type CloseBehavior = 'exit' | 'background';\n");
    out.push('\n');
    out.push_str("/** Generated command name → successful return DTO contract. */\n");
    out.push_str("export interface IpcCommandResultMap {\n");
    out.push_str("  readonly get_bootstrap_state: BootstrapSnapshot;\n");
    out.push_str("  readonly library_status: LibraryStatus;\n");
    out.push_str("  readonly all_songs: PagedSongs;\n");
    out.push_str("  readonly search: PagedSongs;\n");
    out.push_str("  readonly favorites: PagedSongs;\n");
    out.push_str("  readonly recent: readonly SongView[];\n");
    out.push_str("  readonly catalog_collections: readonly CatalogCollectionView[];\n");
    out.push_str("  readonly catalog_collection_songs: readonly SongView[];\n");
    out.push_str("  readonly set_artist_cover: void;\n");
    out.push_str("  readonly library_counts: LibraryCountsDto;\n");
    out.push_str("  readonly playlists: readonly PlaylistView[];\n");
    out.push_str("  readonly playlist_members: readonly SongView[];\n");
    out.push_str("  readonly song_detail: SongDetailView;\n");
    out.push_str("  readonly song_cover_keys: Readonly<Record<string, string>>;\n");
    out.push_str("  readonly set_favorite: SongView;\n");
    out.push_str("  readonly create_playlist: string;\n");
    out.push_str("  readonly rename_playlist: void;\n");
    out.push_str("  readonly set_playlist_cover: void;\n");
    out.push_str("  readonly delete_playlist: void;\n");
    out.push_str("  readonly add_to_playlists: void;\n");
    out.push_str("  readonly remove_playlist_song: void;\n");
    out.push_str("  readonly delete_song: string;\n");
    out.push_str("  readonly undo_delete: string;\n");
    out.push_str("  readonly choose_library_root: LibraryRootStatusDto | null;\n");
    out.push_str("  readonly choose_and_import_files: ImportBatchDto | null;\n");
    out.push_str("  readonly reveal_song: RevealResultDto;\n");
    out.push_str("  readonly start_scan: ScanSnapshot;\n");
    out.push_str("  readonly cancel_scan: boolean;\n");
    out.push_str("  readonly set_theme: void;\n");
    out.push_str("  readonly set_close_behavior: void;\n");
    out.push_str("  readonly get_close_behavior: CloseBehavior;\n");
    out.push_str("  readonly play_playlist_context: void;\n");
    out.push_str("  readonly play_library_context: void;\n");
    out.push_str("  readonly restore_playback_session: string;\n");
    out.push_str("  readonly file_open_frontend_ready: void;\n");
    out.push_str("  readonly play_temporary_file: void;\n");
    out.push_str("  readonly import_current_temporary_file: ImportResultDto;\n");
    out.push_str("  readonly player_control: void;\n");
    out.push_str("  readonly queue_command: void;\n");
    out.push_str("  readonly set_volume: void;\n");
    out.push_str("  readonly toggle_mute: void;\n");
    out.push_str("  readonly seek: void;\n");
    out.push_str("  readonly get_lyrics: SongLyricsDto;\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Drift detection: the committed generated file must equal the current
    /// generator output. CI additionally runs `git diff --exit-code`, but this
    /// test makes `cargo test -p echo-desktop` catch the same divergence.
    #[test]
    fn committed_generated_file_is_in_sync_with_the_generator() {
        let committed = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .expect("crate dir")
                .parent()
                .expect("workspace")
                .join("apps/desktop/src/ipc/ipc-types.generated.ts"),
        )
        .expect("generated file committed");
        assert_eq!(
            committed,
            generated_typescript(),
            "IPC types drifted; run `cargo run -p echo-desktop --bin echo-generate-ipc` and commit"
        );
    }

    #[test]
    fn generated_types_are_readonly_and_camel_case() {
        let ts = generated_typescript();
        assert!(ts.contains("readonly "), "all fields readonly");
        assert!(ts.contains("relativePath"), "camelCase field");
        assert!(ts.contains("nextCursor"), "camelCase field");
        assert!(!ts.contains("relative_path"), "no snake_case leaks");
        assert!(!ts.contains("absolutePath"), "no absolute path type");
        assert!(ts.contains("IpcErrorDto"), "error DTO present");
        assert!(
            ts.contains("export interface IpcCommandResultMap"),
            "command return contract present"
        );
        assert!(
            !ts.contains(": unknown;"),
            "command return contracts must never fall back to unknown"
        );
        // Determinism: run twice -> identical.
        assert_eq!(ts, generated_typescript());
    }

    #[test]
    fn generated_types_dont_materialize_private_impl_details() {
        let ts = generated_typescript();
        let forbidden = ["Mutex", "ScanDeps", "PathBuf", "core::", "echo_core"];
        for token in forbidden {
            assert!(!ts.contains(token), "ICD leaks {token}");
        }
    }
}
